# Generated by Django 3.0.6 on 2020-08-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('categories', models.CharField(max_length=100)),
                ('average_rating', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
                ('thumbnail', models.URLField()),
            ],
        ),
    ]
