# Generated by Django 3.0.6 on 2020-08-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
