# Generated by Django 3.0.6 on 2020-08-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20200813_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
